export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua & Deps",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Central African Rep",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo {Democratic Rep}",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland {Republic}",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea North",
  "Korea South",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar, {Burma}",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "St Kitts & Nevis",
  "St Lucia",
  "Saint Vincent & the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome & Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Trinidad & Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const IndianStates = [
  {
    name: "Andaman and Nicobar Islands",
    districts: [
      {
        name: "Nicobars",
        areas: ["Car Nicobar", "Great Nicobar", "Nancowry"],
      },
      {
        name: "North And Middle Andaman",
        areas: ["Diglipur", "Mayabunder", "Rangat"],
      },
      {
        name: "South Andamans",
        areas: ["Ferrargunj", "Little Andaman", "Prothrapur", "Port Blair"],
      },
    ],
  },
  {
    name: "Andhra Pradesh",
    districts: [
      {
        name: "Anantapur",
        areas: ["Anantapur", "Kalyandurg", "Kadiri", "Hindupur", "Gooty", "Penukonda", "Rayadurg"],
      },
      {
        name: "Chittoor",
        areas: ["Chittoor", "Tirupati", "Madanapalle", "Puttur", "Srikalahasti", "Nagari"],
      },
      {
        name: "Eluru",
        areas: ["Eluru", "Bhimavaram", "Kovvur", "Nidadavolu", "Tadepalligudem"],
      },
      {
        name: "Guntur",
        areas: ["Guntur", "Tenali", "Narasaraopet", "Chilakaluripet", "Repalle", "Macherla", "Vinukonda"],
      },
      {
        name: "Kadapa",
        areas: ["Kadapa", "Jammalamadugu", "Proddatur", "Pulivendula", "Badvel"],
      },
      {
        name: "Kakinada",
        areas: ["Kakinada", "Peddapuram", "Tuni", "Prathipadu", "Samalkota", "Rajahmundry"],
      },
      {
        name: "Krishna",
        areas: ["Machilipatnam", "Vijayawada", "Gudivada", "Nuzvid", "Pedana", "Kaikaluru"],
      },
      {
        name: "Kurnool",
        areas: ["Kurnool", "Adoni", "Yemmiganur", "Nandyal", "Allagadda", "Dhone", "Koilkuntla"],
      },
      {
        name: "Nellore",
        areas: ["Nellore", "Gudur", "Kandukur", "Kavali", "Atmakur", "Venkatagiri"],
      },
      {
        name: "Parvathipuram",
        areas: ["Parvathipuram", "Bobilli", "Salur", "Cheepurupalli", "Gajapathinagaram"],
      },
      {
        name: "Prakasam",
        areas: ["Ongole", "Chirala", "Markapur", "Kandukur", "Giddaluru"],
      },
      {
        name: "Srikakulam",
        areas: ["Srikakulam", "Ichchapuram", "Palasa", "Tekkali", "Amudalavalasa"],
      },
      {
        name: "Visakhapatnam",
        areas: ["Visakhapatnam", "Anakapalle", "Narsipatnam", "Payakaraopeta", "Chodavaram"],
      },
      {
        name: "Vizianagaram",
        areas: ["Vizianagaram", "Bobilli", "Cheepurupalli", "Gajapathinagaram", "Salur", "Sathupalli"],
      },
      {
        name: "YSR Kadapa",
        areas: ["Jammalamadugu", "Proddatur", "Pulivendula", "Badvel", "Kadapa"],
      },
    ],
  },
  {
    name: "Arunachal Pradesh",
    districts: [
      {
        name: "Changlang",
        areas: ["Changlang", "Jairampur", "Miao", "Bordumsa"],
      },
      {
        name: "East Kameng",
        areas: ["Seppa", "Lichabari", "Pakke-Kasang"],
      },
      {
        name: "East Siang",
        areas: ["Pasighat", "Mebo", "Kotliang"],
      },
      {
        name: "Papum Pare",
        areas: ["Yupia", "Itanagar", "Silsang", "Sagalee"],
      },
      {
        name: "Tawang",
        areas: ["Tawang", "Lumla", "Jang"],
      },
    ],
  },
  {
    name: "Assam",
    districts: [
      {
        name: "Kokrajhar",
        areas: ["Kokrajhar", "Gossaigaon", "Kokrajhar Town"],
      },
      {
        name: "Dhubri",
        areas: ["Dhubri", "Bilasipara", "Tamlhat"],
      },
    ],
  },
  {
    name: "Bihar",
    districts: [
      {
        name: "Arwal",
        areas: ["Arwal", "Kurtha", "Karpi", "Sonpurwa"],
      },
      {
        name: "Jehanabad",
        areas: ["Jehanabad", "Gho Si", "Modanganj", "Arwal"],
      },
    ],
  },
  {
    name: "Goa",
    districts: [
      {
        name: "North Goa",
        areas: ["Panaji", "Mapusa", "Bicholim", "Porvorim"],
      },
      {
        name: "South Goa",
        areas: ["Margao", "Vasco da Gama", "Ponda", "Cuncolim"],
      },
    ],
  },
  {
    name: "Chhattisgarh",
    districts: [
      {
        name: "Bilaspur",
        areas: ["Bilaspur", "Takhatpur", "Bilha"],
      },
      {
        name: "Raipur",
        areas: ["Raipur", "Abhanpur", "Arang", "Bemetara"],
      },
    ],
  },
  {
    name: "Gujarat",
    districts: [
      {
        name: "Ahmedabad",
        areas: ["Ahmedabad", "Vastrapur", "Maninagar", "Paldi"],
      },
      {
        name: "Surat",
        areas: ["Surat", "Adajan", "Athwa", "Katargam"],
      },
    ],
  },
  {
    name: "Haryana",
    districts: [
      {
        name: "Gurugram",
        areas: [
          "Gurugram",
          "Faridabad",
          "Ambience Mall Road",
          "Sohna Road",
          "DLF Phase I",
          "DLF Phase II",
          "DLF Phase III",
          "DLF Phase IV",
          "DLF Phase V",
          "Sikanderpur",
          "Sultanpur",
          "Sohna",
          "Badshapur",
        ],
      },
    ],
  },
  {
    name: "Himachal Pradesh",
    districts: [
      {
        name: "Shimla",
        areas: ["Shimla", "Kasauli", "Chail", "Mashobra"],
      },
    ],
  },
  {
    name: "Jharkhand",
    districts: [
      {
        name: "Ranchi",
        areas: ["Ranchi", "Kanke", "Hatia", "Harmu"],
      },
    ],
  },
  {
    name: "Karnataka",
    districts: [
      {
        name: "Bangalore",
        areas: ["Bangalore", "Koramangala", "Indiranagar", "Jayanagar"],
      },
    ],
  },
  {
    name: "Kerala",
    districts: [
      {
        name: "Thiruvananthapuram",
        areas: ["Thiruvananthapuram", "Kovalam", "Varkala"],
      },
    ],
  },
  {
    name: "Madhya Pradesh",
    districts: [
      {
        name: "Bhopal",
        areas: ["Bhopal", "Habibganj", "Indira Nagar"],
      },
    ],
  },
  {
    name: "Manipur",
    districts: [
      {
        name: "Imphal",
        areas: ["Imphal", "Thoubal", "Bishnupur"],
      },
    ],
  },
  {
    name: "Meghalaya",
    districts: [
      {
        name: "Shillong",
        areas: ["Shillong", "Mawlynnong", "Jowai"],
      },
    ],
  },
  {
    name: "Mizoram",
    districts: [
      {
        name: "Aizawl",
        areas: ["Aizawl", "Lunglei", "Saiha"],
      },
    ],
  },
  {
    name: "Nagaland",
    districts: [
      {
        name: "Kohima",
        areas: ["Kohima", "Dimapur", "Mokokchung"],
      },
    ],
  },
  {
    name: "Odisha",
    districts: [
      {
        name: "Bhubaneswar",
        areas: ["Bhubaneswar", "Puri", "Cuttack"],
      },
    ],
  },
  {
    name: "Punjab",
    districts: [
      {
        name: "Ludhiana",
        areas: ["Ludhiana", "Amritsar", "Jalandhar"],
      },
    ],
  },
  {
    name: "Rajasthan",
    districts: [
      {
        name: "Jaipur",
        areas: ["Jaipur", "Jodhpur", "Udaipur"],
      },
    ],
  },
  {
    name: "Sikkim",
    districts: [
      {
        name: "Gangtok",
        areas: ["Gangtok", "Namchi", "Geyzing"],
      },
    ],
  },
  {
    name: "Tamil Nadu",
    districts: [
      {
        name: "Chennai",
        areas: ["Chennai", "Madurai", "Coimbatore"],
      },
    ],
  },
  {
    name: "Telangana",
    districts: [
      {
        name: "Hyderabad",
        areas: ["Hyderabad", "Warangal", "Karimnagar"],
      },
    ],
  },
  {
    name: "Tripura",
    districts: [
      {
        name: "Agartala",
        areas: ["Agartala", "Udaipur", "Belonia"],
      },
    ],
  },
  {
    name: "Uttar Pradesh",
    districts: [
      {
        name: "Lucknow",
        areas: ["Lucknow", "Agra", "Varanasi"],
      },
    ],
  },
  {
    name: "Uttarakhand",
    districts: [
      {
        name: "Dehradun",
        areas: ["Dehradun", "Haridwar", "Nainital"],
      },
    ],
  },
  {
    name: "West Bengal",
    districts: [
      {
        name: "Alipurduar",
        areas: ["Alipurduar I", "Alipurduar II", "Falakata", "Kalchini", "Kumargram", "Madarihat"],
      },
      {
        name: "Nadia",
        areas: ["Krishnanagar", "Ranaghat", "Kalyani", "Santipur"],
      },
    ],
  },
  {
    name: "Maharashtra",
    districts: [
      {
        name: "Mumbai",
        areas: [
          "Andheri",
          "Borivali",
          "Chembur",
          "Dadar",
          "Juhu",
          "Kandivali",
          "Kurla",
          "Malad",
          "Mira-Bhayandar",
          "Mulund",
          "Santacruz",
          "Thane",
          "Vasai",
        ],
      },
      {
        name: "Pune",
        areas: ["Hadapsar", "Kondhwa", "Kothrud", "Mundhwa", "Shivaji Nagar", "Wagholi", "Wanowrie", "Yerwada"],
      },
      {
        name: "Nagpur",
        areas: [
          "Ambazari",
          "Gittikhadan",
          "Indora",
          "Kalamna",
          "Kamla Nehru Nagar",
          "Mangalwari",
          "Sitabuldi",
          "Sneh Nagar",
          "Wardha Road",
        ],
      },
      {
        name: "Nashik",
        areas: [
          "Adgaon",
          "Ambad",
          "Dwarka",
          "Gangapur Road",
          "Indira Nagar",
          "Jalgaon Road",
          "Lasalgaon",
          "Makhmalabad",
          "Nashik Road",
          "Peth",
          "Sinnar",
        ],
      },
      {
        name: "Aurangabad",
        areas: [
          "Aurangabad East",
          "Aurangabad West",
          "Gangapur",
          "Jalna Road",
          "Khamgaon",
          "Paithan",
          "Sillod",
          "Vaijapur",
        ],
      },
    ],
  },
];

export const professions = [
  "Teacher",
  "Engineer",
  "Doctor",
  "Lawyer",
  "Accountant",
  "Architect",
  "Software Developer",
  "Data Scientist",
  "Project Manager",
  "Marketing Manager",
  "Sales Manager",
  "HR Manager",
  "Financial Analyst",
  "Business Analyst",
  "Consultant",
  "Graphic Designer",
  "Web Designer",
  "UI/UX Designer",
  "Content Writer",
  "Translator",
  "Editor",
  "Photographer",
  "Videographer",
  "Animator",
  "Musician",
  "Actor",
  "Dancer",
  "Chef",
  "Hotel Manager",
  "Travel Agent",
  "Real Estate Agent",
  "Insurance Agent",
  "Customer Service Representative",
  "Receptionist",
  "Administrative Assistant",
  "Data Entry Clerk",
  "Librarian",
  "Social Worker",
  "Journalist",
  "Reporter",
  "Pilot",
  "Air Hostess",
  "Sailor",
  "Driver",
  "Mechanic",
  "Electrician",
  "Plumber",
  "Carpenter",
  "Painter",
  "Welder",
  "Mason",
  "Gardener",
  "Housekeeper",
  "Delivery Person",
  "Security Guard",
  "Police Officer",
  "Firefighter",
  "Paramedic",
  "Nurse",
  "Physiotherapist",
  "Pharmacist",
  "Dentist",
  "Veterinarian",
  "Judge",
  "Politician",
  "Diplomat",
  "Researcher",
  "Professor",
  "Student",
  "Retired",
  "Unemployed",
  "Other",
];

export const educations = [
  "5th Pass",
  "8th Pass",
  "10th Pass",
  "12th Pass",
  "Diploma",
  "B.A.",
  "B.Sc.",
  "B.Com.",
  "B.Tech / B.E.",
  "MBBS",
  "BBA",
  "BCA",
  "LLB",
  "M.A.",
  "M.Sc.",
  "M.Com.",
  "M.Tech",
  "M.E.",
  "MBA",
  "MCA",
  "LLM",
  "Ph.D.",
  "M.Phil.",
];

export const contributionAreas = [
  "Education",
  "Healthcare",
  "Technology",
  "Environment",
  "Community Service",
  "Event Management",
  "Mentorship",
  "Training Workshops",
  "Content Creation",
  "Marketing Outreach",
  "Fundraising",
  "Logistics Support",
  "Research",
  "Data Analysis",
  "Social Work",
  "Animal Care",
  "Legal Support",
  "Other",
];

// const items: Item[] = [
//   {
//     id: "1",
//     product: "Black Chair",
//     productImage: "https://cdn.shadcnstudio.com/ss-assets/products/product-1.png",
//     fallback: "BC",
//     price: 159,
//     availability: "In Stock",
//     rating: 3.9,
//   },
//   {
//     id: "2",
//     product: "Nike Jordan",
//     productImage: "https://cdn.shadcnstudio.com/ss-assets/products/product-2.png",
//     fallback: "NJ",
//     price: 599,
//     availability: "Limited",
//     rating: 4.4,
//   },
//   {
//     id: "3",
//     product: "OnePlus 7 Pro",
//     productImage: "https://cdn.shadcnstudio.com/ss-assets/products/product-3.png",
//     fallback: "O7P",
//     price: 1299,
//     availability: "Out of Stock",
//     rating: 3.5,
//   },
//   {
//     id: "4",
//     product: "Nintendo Switch",
//     productImage: "https://cdn.shadcnstudio.com/ss-assets/products/product-4.png",
//     fallback: "NS",
//     price: 499,
//     availability: "In Stock",
//     rating: 4.9,
//   },
//   {
//     id: "5",
//     product: "Apple magic mouse",
//     productImage: "https://cdn.shadcnstudio.com/ss-assets/products/product-5.png",
//     fallback: "AMM",
//     price: 970,
//     availability: "Limited",
//     rating: 4.1,
//   },
//   {
//     id: "6",
//     product: "Apple watch",
//     productImage: "https://cdn.shadcnstudio.com/ss-assets/products/product-6.png",
//     fallback: "AW",
//     price: 1500,
//     availability: "Limited",
//     rating: 3.1,
//   },
//   {
//     id: "7",
//     product: "Casio G-Shock",
//     productImage: "https://cdn.shadcnstudio.com/ss-assets/products/product-8.png",
//     fallback: "CGS",
//     price: 194,
//     availability: "Out of Stock",
//     rating: 1.5,
//   },
//   {
//     id: "8",
//     product: "RayBan Sunglasses",
//     productImage: "https://cdn.shadcnstudio.com/ss-assets/products/product-10.png",
//     fallback: "RBS",
//     price: 199,
//     availability: "Out of Stock",
//     rating: 2.4,
//   },
// ];
